import os
from matplotlib import pyplot as plt
import numpy as np
import sys
from scipy.signal import hilbert

if len(sys.argv) !=2:
    print("Usage: {} <output generated by ngspice>".format(sys.argv[0]))
    exit(1)



with open(sys.argv[1],'r') as f:
    txt = f.read()


txt = txt.split('\n')
t = []
v = []


for i,line in enumerate(txt):
    if line.strip() == '':
        continue
    vv = float(line.split()[1])
    tt = float(line.split()[0])
    if i==0 and vv==0:
        continue
    t.append(tt)
    v.append(vv)

dt = np.mean(np.diff(t))
V = np.abs(np.fft.fft(v))
freqs = np.fft.fftfreq(len(V), dt)
plt.plot(freqs, V)

plt.show()
